root: true
parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

plugins:
  - '@typescript-eslint'

rules:
  # Library rules
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/prefer-interface': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/no-unnecessary-condition': error

  '@typescript-eslint/no-unused-vars':
    - error
    - destructuredArrayIgnorePattern: "^_"
      argsIgnorePattern: "^_"

  '@typescript-eslint/indent':
    - error
    - 4

  # ESLint rules
  no-unused-vars: off
  no-compare-neg-zero: error
  no-template-curly-in-string: error
  no-unsafe-negation: error
  accessor-pairs: warn
  array-callback-return: error
  complexity: warn
  no-floating-decimal: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal: error
  no-return-assign: error
  no-return-await: error
  no-self-compare: error
  no-sequences: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  prefer-promise-reject-errors: error
  require-await: warn
  yoda: error
  no-label-var: error
  no-shadow: off
  no-undef-init: error
  callback-return: error
  getter-return: off
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  array-bracket-spacing: off
  block-spacing: error
  dot-notation: error
  eqeqeq: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  func-names: error
  func-name-matching: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  template-tag-spacing: error
  unicode-bom: error
  arrow-spacing: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  prefer-arrow-callback: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  template-curly-spacing: off
  yield-star-spacing: error
  no-array-constructor: error
  no-lonely-if: error
  no-mixed-operators: error
  no-new-object: error
  no-trailing-spaces: off
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  semi-spacing: error
  space-before-blocks: off
  key-spacing: error
  keyword-spacing: error
  max-depth: error
  operator-assignment: error
  new-cap: off

  semi:
    - error
    - always

  curly:
    - error
    - multi-line
    - consistent

  dot-location:
    - error
    - property

  no-empty-function:
    - error
    - allow:
        - constructors

  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true

  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true

  comma-dangle:
    - error
    - never

  consistent-this:
    - error
    - $this

  func-style:
    - error
    - declaration
    - allowArrowFunctions: true

  indent:
    - error
    - 4
    - SwitchCase: 1

  max-nested-callbacks:
    - error
    - max: 4

  max-statements-per-line:
    - error
    - max: 2

  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 3

  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0

  object-curly-spacing:
    - error
    - always

  padded-blocks:
    - error
    - never

  quote-props:
    - error
    - as-needed

  quotes:
    - error
    - double
    - avoidEscape: true
      allowTemplateLiterals: true

  space-before-function-paren:
    - error
    - asyncArrow: always
      anonymous: never
      named: never

  arrow-parens:
    - error
    - as-needed