logging:
  default_scoping:
    include_channels: ["test"]

  logs:
    - channel_id: "1025475523440291935"
      events:
        - message_delete
      scoping:
        exclude_channels: ["test"]
    - channel_id: "1025475523440291935"
      events:
        - message_delete