name: CI
on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
    
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run ESLint
        run: eslint .
